"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferManager__factory = exports.MockERC20__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var MockERC20__factory_1 = require("./MockERC20__factory");
Object.defineProperty(exports, "MockERC20__factory", { enumerable: true, get: function () { return MockERC20__factory_1.MockERC20__factory; } });
var TransferManager__factory_1 = require("./TransferManager__factory");
Object.defineProperty(exports, "TransferManager__factory", { enumerable: true, get: function () { return TransferManager__factory_1.TransferManager__factory; } });
