/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockERC20__factory } from "./MockERC20__factory";
export { TransferManager__factory } from "./TransferManager__factory";
